Download phase
oVirt/ovirt-imageio pull request #111
Opened 2022-07-27 16:11 UTC by nirs

Show download phases during download-disk.

Rebased on #110

2022-07-27 17:01 UTC, rokkbert commented
If we use interactive password entry, the progressbar should not be drawn first, otherwise both go in the same line and it looks like this:
![image](https://user-images.githubusercontent.com/5221547/181306215-17516378-095a-4d45-b309-9ec4db125509.png)

2022-07-27 17:07 UTC, rokkbert requested changes
Looks cool and informative, except for the interactive-password-case.

2022-07-27 17:33 UTC, nirs commented on ovirt_imageio/client/_download.py
> +        con = _ovirt.connect(args)
Good catch!

2022-07-27 18:35 UTC, nirs commented on ovirt_imageio/client/_download.py
> +        con = _ovirt.connect(args)
Fixed in current version by moving password reading to the parser. This way the input does not clash with the output, and we can create the progress very early so it cover the entire operation.

2022-07-28 08:24 UTC, aesteve-rh approved these changes
Nice!

It would be great to find a way to separate the transfer part from the other phases, so that the speed rate does not decrease in the progress bar updates while finalizing. 

Not for this PR, though!

2022-07-28 08:55 UTC, nirs commented
> It would be great to find a way to separate the transfer part from the other phases, so that the speed rate does not decrease in the progress bar updates while finalizing.

True, the rate is relevant relevant for the download phase, but from
user point of view, the total time to download matters. This just show
the horrible inefficiency we have in engine. But with real disks which
may be 100's of GiB and slower storage and network download will take
minutes and few seconds to finalize the transfers are negligible.

If we want to avoid this we can use the progress style of the sdk examples:

    [   0.00 ] creating transfer
    [   0.72 ] downloading image
    [   100% ] 6.00 GiB, 2.67 s, 2.25 GiB/s
    [   2.70 ] finalizing transfer
    [   7.81 ] download completed

With this we get accurate transfer stats, and the total time to download, but the transfer
stats are misleading.

2022-07-28 08:55 UTC, merged